id: medcom.fhir.dk.core
canonical: http://medcomfhir.dk/ig/core
name: MedComCore
title: "Danish MedCom Core"
description: Danish MedCom Core IG
status: active
version: "2.2.0"
fhirVersion: 4.0.1
copyrightYear: 2021+
releaseLabel: Release
publisher:
  name: MedCom
  url: http://www.medcom.dk
jurisdiction: urn:iso:std:iso:3166#DK "Denmark"
dependencies:
  hl7.fhir.dk.core: 
    uri: https://hl7.dk/fhir/core/2.0.0/
    version: 2.0.0
  medcom.fhir.dk.terminology: 1.4.0
menu:
  Table of Contents: toc.html
  Home: index.html
  Profiles: profiles.html
  Extensions: extensions.html
  Artifacts: artifacts.html
  Downloads: downloads.html

parameters:
  apply-contact: true
  apply-jurisdiction: true
  apply-publisher: true
