id: medcom.fhir.dk.core
canonical: http://medcomfhir.dk/ig/core
name: MedComCore
title: "DK MedCom Core"
description: This IG includes core profiles defined by MedCom. These profiles are used in MedCom's FHIR standards
status: active
version: 3.0.2-dev
fhirVersion: 4.0.1
copyrightYear: 2021+
releaseLabel: release
publisher:
  name: MedCom
  url: http://www.medcom.dk
jurisdiction: urn:iso:std:iso:3166#DK "Denmark"

dependencies:
  hl7.fhir.dk.core: 3.4.0
  medcom.fhir.dk.terminology: 2.0.1
  hl7.fhir.extensions.r5: 4.0.1

menu:
  Home: index.html
  Profiles: profiles.html
  Extensions: extensions.html
  Artifacts: artifacts.html
  More:
    Table of Contents: toc.html
    Downloads: downloads.html
    Dependencies: dependencies.html

parameters:
  apply-contact: true
  apply-jurisdiction: true
  apply-publisher: true
  pin-canonicals: pin-multiples
  excludettl: true
